In [273]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [274]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [275]:
df.shape

(569, 33)

In [276]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [277]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [278]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [279]:
X_train

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
197,18.080,21.84,117.40,1024.0,0.07371,0.08642,0.11030,0.057780,0.1770,0.05340,...,19.76,24.70,129.10,1228.0,0.08822,0.19630,0.2535,0.09181,0.2369,0.06558
488,11.680,16.17,75.49,420.5,0.11280,0.09263,0.04279,0.031320,0.1853,0.06401,...,13.32,21.59,86.57,549.8,0.15260,0.14770,0.1490,0.09815,0.2804,0.08024
396,13.510,18.89,88.10,558.1,0.10590,0.11470,0.08580,0.053810,0.1806,0.06079,...,14.80,27.20,97.33,675.2,0.14280,0.25700,0.3438,0.14530,0.2666,0.07686
548,9.683,19.34,61.05,285.7,0.08491,0.05030,0.02337,0.009615,0.1580,0.06235,...,10.93,25.59,69.10,364.2,0.11990,0.09546,0.0935,0.03846,0.2552,0.07920
474,10.880,15.62,70.41,358.9,0.10070,0.10690,0.05115,0.015710,0.1861,0.06837,...,11.94,19.35,80.78,433.1,0.13320,0.38980,0.3365,0.07966,0.2581,0.10800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,17.350,23.06,111.00,933.1,0.08662,0.06290,0.02891,0.028370,0.1564,0.05307,...,19.85,31.47,128.20,1218.0,0.12400,0.14860,0.1211,0.08235,0.2452,0.06515
566,16.600,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.053020,0.1590,0.05648,...,18.98,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.14180,0.2218,0.07820
300,19.530,18.90,129.50,1217.0,0.11500,0.16420,0.21970,0.106200,0.1792,0.06552,...,25.93,26.24,171.10,2053.0,0.14950,0.41160,0.6121,0.19800,0.2968,0.09929
434,14.860,16.94,94.89,673.7,0.08924,0.07074,0.03346,0.028770,0.1573,0.05703,...,16.31,20.54,102.30,777.5,0.12180,0.15500,0.1220,0.07971,0.2525,0.06827
79,12.860,18.00,83.19,506.3,0.09934,0.09546,0.03889,0.023150,0.1718,0.05997,...,14.24,24.82,91.88,622.1,0.12890,0.21410,0.1731,0.07926,0.2779,0.07918

In [280]:
X_test

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
340,14.42,16.54,94.15,641.2,0.09751,0.11390,0.08007,0.04223,0.1912,0.06412,...,16.67,21.51,111.40,862.1,0.12940,0.3371,0.3755,0.14140,0.3053,0.08764
211,11.84,18.94,75.51,428.0,0.08871,0.06900,0.02669,0.01393,0.1533,0.06057,...,13.30,24.99,85.22,546.3,0.12800,0.1880,0.1471,0.06913,0.2535,0.07993
447,14.80,17.66,95.88,674.8,0.09179,0.08890,0.04069,0.02260,0.1893,0.05886,...,16.43,22.74,105.90,829.5,0.12260,0.1881,0.2060,0.08308,0.3600,0.07285
528,13.94,13.17,90.31,594.2,0.12480,0.09755,0.10100,0.06615,0.1976,0.06457,...,14.62,15.38,94.52,653.3,0.13940,0.1364,0.1559,0.10150,0.2160,0.07253
7,13.71,20.83,90.20,577.9,0.11890,0.16450,0.09366,0.05985,0.2196,0.07451,...,17.06,28.14,110.60,897.0,0.16540,0.3682,0.2678,0.15560,0.3196,0.11510
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,12.10,17.72,78.07,446.2,0.10290,0.09758,0.04783,0.03326,0.1937,0.06161,...,13.56,25.80,88.33,559.5,0.14320,0.1773,0.1603,0.06266,0.3049,0.07081
243,13.75,23.77,88.54,590.0,0.08043,0.06807,0.04697,0.02344,0.1773,0.05429,...,15.01,26.34,98.00,706.0,0.09368,0.1442,0.1359,0.06106,0.2663,0.06321
376,10.57,20.22,70.15,338.3,0.09073,0.16600,0.22800,0.05941,0.2188,0.08450,...,10.85,22.82,76.51,351.9,0.11430,0.3619,0.6030,0.14650,0.2597,0.12000
195,12.91,16.33,82.53,516.4,0.07941,0.05366,0.03873,0.02377,0.1829,0.05667,...,13.88,22.00,90.81,600.6,0.10970,0.1506,0.1764,0.08235,0.3024,0.06949
124,13.37,16.39,86.10,553.5,0.07115,0.07325,0.08092,0.02800,0.1422,0.05823,...,14.26,22.75,91.99,632.1,0.10250,0.2531,0.3308,0.08978,0.2048,0.07628

In [281]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [282]:
X_train

array([[ 1.10491411,  0.52887325,  1.02784502, ..., -0.36539838,
        -0.8898801 , -1.04152148],
       [-0.69843278, -0.77503889, -0.6837251 , ..., -0.27054152,
        -0.20404152, -0.24456411],
       [-0.18278828, -0.14952901, -0.16874301, ...,  0.4349002 ,
        -0.4216179 , -0.42831008],
       ...,
       [ 1.51348489, -0.14722934,  1.52199912, ...,  1.22337907,
         0.0545275 ,  0.79104558],
       [ 0.1976052 , -0.5979644 ,  0.10855503, ..., -0.54643432,
        -0.6439242 , -0.89528578],
       [-0.3659407 , -0.35419952, -0.3692634 , ..., -0.55316706,
        -0.24345753, -0.30218858]])

In [283]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test= encoder.fit_transform(y_test)

In [284]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor =torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [285]:
import torch.nn as nn

In [286]:
class MySimpleNN(nn.Module):
  def __init__(self, num_features):
    super().__init__()

    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()


  def forward(self, num_features):
    out = self.linear(num_features)
    out = self.sigmoid(out)
    return out

In [287]:
loss_function= nn.BCELoss()

In [288]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [289]:
learning_rate = 0.01

In [290]:
epochs = 250

In [291]:
# create model
model = MySimpleNN(num_features=X_train_tensor.shape[1])
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
for epoch in range(epochs):
  y_pred= model(X_train_tensor)

  # loss functions
  loss =loss_function(y_pred, y_train_tensor.view(-1, 1))
  optimizer.zero_grad()
  # backward pass
  loss.backward()

 # optimzer
  optimizer.step()



  print(f'Epoch: {epoch  + 1} Loss: {loss.item()}')

Epoch: 1 Loss: 1.0098155736923218
Epoch: 2 Loss: 0.9721969366073608
Epoch: 3 Loss: 0.9364790320396423
Epoch: 4 Loss: 0.9026359915733337
Epoch: 5 Loss: 0.87063068151474
Epoch: 6 Loss: 0.8404157161712646
Epoch: 7 Loss: 0.8119344115257263
Epoch: 8 Loss: 0.7851215600967407
Epoch: 9 Loss: 0.7599055767059326
Epoch: 10 Loss: 0.7362098097801208
Epoch: 11 Loss: 0.7139535546302795
Epoch: 12 Loss: 0.6930540204048157
Epoch: 13 Loss: 0.6734276413917542
Epoch: 14 Loss: 0.6549912691116333
Epoch: 15 Loss: 0.6376637816429138
Epoch: 16 Loss: 0.6213664412498474
Epoch: 17 Loss: 0.6060242652893066
Epoch: 18 Loss: 0.5915664434432983
Epoch: 19 Loss: 0.5779266953468323
Epoch: 20 Loss: 0.5650432705879211
Epoch: 21 Loss: 0.5528595447540283
Epoch: 22 Loss: 0.5413230061531067
Epoch: 23 Loss: 0.5303858518600464
Epoch: 24 Loss: 0.520004153251648
Epoch: 25 Loss: 0.5101378560066223
Epoch: 26 Loss: 0.5007504820823669
Epoch: 27 Loss: 0.4918084740638733
Epoch: 28 Loss: 0.48328137397766113
Epoch: 29 Loss: 0.47514134645462036
Epoch: 30 Loss: 0.4673627018928528
Epoch: 31 Loss: 0.4599221646785736
Epoch: 32 Loss: 0.45279809832572937
Epoch: 33 Loss: 0.4459708034992218
Epoch: 34 Loss: 0.4394221007823944
Epoch: 35 Loss: 0.4331352412700653
Epoch: 36 Loss: 0.4270947575569153
Epoch: 37 Loss: 0.42128628492355347
Epoch: 38 Loss: 0.41569674015045166
Epoch: 39 Loss: 0.4103137254714966
Epoch: 40 Loss: 0.40512600541114807
Epoch: 41 Loss: 0.40012291073799133
Epoch: 42 Loss: 0.3952946066856384
Epoch: 43 Loss: 0.39063212275505066
Epoch: 44 Loss: 0.38612669706344604
Epoch: 45 Loss: 0.381770521402359
Epoch: 46 Loss: 0.37755605578422546
Epoch: 47 Loss: 0.37347647547721863
Epoch: 48 Loss: 0.36952513456344604
Epoch: 49 Loss: 0.36569610238075256
Epoch: 50 Loss: 0.36198344826698303
Epoch: 51 Loss: 0.35838189721107483
Epoch: 52 Loss: 0.35488635301589966
Epoch: 53 Loss: 0.3514922559261322
Epoch: 54 Loss: 0.34819483757019043
Epoch: 55 Loss: 0.3449900448322296
Epoch: 56 Loss: 0.3418739438056946
Epoch: 57 Loss: 0.33884263038635254
Epoch: 58 Loss: 0.3358927369117737
Epoch: 59 Loss: 0.33302077651023865
Epoch: 60 Loss: 0.3302236795425415
Epoch: 61 Loss: 0.32749834656715393
Epoch: 62 Loss: 0.3248419761657715
Epoch: 63 Loss: 0.32225194573402405
Epoch: 64 Loss: 0.3197256326675415
Epoch: 65 Loss: 0.3172605335712433
Epoch: 66 Loss: 0.3148545026779175
Epoch: 67 Loss: 0.3125052750110626
Epoch: 68 Loss: 0.3102107346057892
Epoch: 69 Loss: 0.30796897411346436
Epoch: 70 Loss: 0.3057780861854553
Epoch: 71 Loss: 0.30363619327545166
Epoch: 72 Loss: 0.30154162645339966
Epoch: 73 Loss: 0.29949286580085754
Epoch: 74 Loss: 0.2974882423877716
Epoch: 75 Loss: 0.2955262362957001
Epoch: 76 Loss: 0.2936055064201355
Epoch: 77 Loss: 0.29172465205192566
Epoch: 78 Loss: 0.2898823618888855
Epoch: 79 Loss: 0.2880774140357971
Epoch: 80 Loss: 0.286308616399765
Epoch: 81 Loss: 0.2845748960971832
Epoch: 82 Loss: 0.28287503123283386
Epoch: 83 Loss: 0.2812080681324005
Epoch: 84 Loss: 0.279572993516922
Epoch: 85 Loss: 0.2779688239097595
Epoch: 86 Loss: 0.27639463543891907
Epoch: 87 Loss: 0.2748495638370514
Epoch: 88 Loss: 0.27333271503448486
Epoch: 89 Loss: 0.2718433141708374
Epoch: 90 Loss: 0.27038055658340454
Epoch: 91 Loss: 0.2689436972141266
Epoch: 92 Loss: 0.26753199100494385
Epoch: 93 Loss: 0.2661447525024414
Epoch: 94 Loss: 0.26478132605552673
Epoch: 95 Loss: 0.2634410262107849
Epoch: 96 Loss: 0.2621232271194458
Epoch: 97 Loss: 0.2608273923397064
Epoch: 98 Loss: 0.25955283641815186
Epoch: 99 Loss: 0.2582990825176239
Epoch: 100 Loss: 0.2570655345916748
Epoch: 101 Loss: 0.25585171580314636
Epoch: 102 Loss: 0.25465714931488037
Epoch: 103 Loss: 0.25348126888275146
Epoch: 104 Loss: 0.2523236572742462
Epoch: 105 Loss: 0.25118380784988403
Epoch: 106 Loss: 0.25006136298179626
Epoch: 107 Loss: 0.2489558756351471
Epoch: 108 Loss: 0.24786688387393951
Epoch: 109 Loss: 0.24679404497146606
Epoch: 110 Loss: 0.24573692679405212
Epoch: 111 Loss: 0.244695246219635
Epoch: 112 Loss: 0.2436685413122177
Epoch: 113 Loss: 0.24265652894973755
Epoch: 114 Loss: 0.24165885150432587
Epoch: 115 Loss: 0.2406751960515976
Epoch: 116 Loss: 0.23970521986484528
Epoch: 117 Loss: 0.23874863982200623
Epoch: 118 Loss: 0.23780512809753418
Epoch: 119 Loss: 0.23687444627285004
Epoch: 120 Loss: 0.23595628142356873
Epoch: 121 Loss: 0.23505035042762756
Epoch: 122 Loss: 0.23415644466876984
Epoch: 123 Loss: 0.23327425122261047
Epoch: 124 Loss: 0.23240353167057037
Epoch: 125 Loss: 0.23154407739639282
Epoch: 126 Loss: 0.23069560527801514
Epoch: 127 Loss: 0.22985795140266418
Epoch: 128 Loss: 0.22903083264827728
Epoch: 129 Loss: 0.2282140702009201
Epoch: 130 Loss: 0.22740745544433594
Epoch: 131 Loss: 0.22661076486110687
Epoch: 132 Loss: 0.2258238047361374
Epoch: 133 Loss: 0.22504638135433197
Epoch: 134 Loss: 0.22427833080291748
Epoch: 135 Loss: 0.2235194444656372
Epoch: 136 Loss: 0.2227695733308792
Epoch: 137 Loss: 0.22202852368354797
Epoch: 138 Loss: 0.22129611670970917
Epoch: 139 Loss: 0.22057221829891205
Epoch: 140 Loss: 0.2198566496372223
Epoch: 141 Loss: 0.21914924681186676
Epoch: 142 Loss: 0.2184499204158783
Epoch: 143 Loss: 0.2177584320306778
Epoch: 144 Loss: 0.2170747071504593
Epoch: 145 Loss: 0.21639856696128845
Epoch: 146 Loss: 0.21572986245155334
Epoch: 147 Loss: 0.2150685042142868
Epoch: 148 Loss: 0.21441435813903809
Epoch: 149 Loss: 0.21376726031303406
Epoch: 150 Loss: 0.21312713623046875
Epoch: 151 Loss: 0.21249380707740784
Epoch: 152 Loss: 0.21186718344688416
Epoch: 153 Loss: 0.21124719083309174
Epoch: 154 Loss: 0.21063363552093506
Epoch: 155 Loss: 0.21002647280693054
Epoch: 156 Loss: 0.20942558348178864
Epoch: 157 Loss: 0.2088308185338974
Epoch: 158 Loss: 0.20824214816093445
Epoch: 159 Loss: 0.20765940845012665
Epoch: 160 Loss: 0.20708253979682922
Epoch: 161 Loss: 0.20651140809059143
Epoch: 162 Loss: 0.20594598352909088
Epoch: 163 Loss: 0.20538613200187683
Epoch: 164 Loss: 0.20483174920082092
Epoch: 165 Loss: 0.2042827606201172
Epoch: 166 Loss: 0.20373910665512085
Epoch: 167 Loss: 0.20320071280002594
Epoch: 168 Loss: 0.2026674449443817
Epoch: 169 Loss: 0.2021392285823822
Epoch: 170 Loss: 0.20161603391170502
Epoch: 171 Loss: 0.20109772682189941
Epoch: 172 Loss: 0.200584277510643
Epoch: 173 Loss: 0.20007559657096863
Epoch: 174 Loss: 0.1995716094970703
Epoch: 175 Loss: 0.19907227158546448
Epoch: 176 Loss: 0.19857746362686157
Epoch: 177 Loss: 0.1980871558189392
Epoch: 178 Loss: 0.19760127365589142
Epoch: 179 Loss: 0.19711974263191223
Epoch: 180 Loss: 0.19664253294467926
Epoch: 181 Loss: 0.19616954028606415
Epoch: 182 Loss: 0.19570069015026093
Epoch: 183 Loss: 0.1952359825372696
Epoch: 184 Loss: 0.19477534294128418
Epoch: 185 Loss: 0.19431866705417633
Epoch: 186 Loss: 0.19386598467826843
Epoch: 187 Loss: 0.19341711699962616
Epoch: 188 Loss: 0.19297213852405548
Epoch: 189 Loss: 0.19253090023994446
Epoch: 190 Loss: 0.19209343194961548
Epoch: 191 Loss: 0.1916595995426178
Epoch: 192 Loss: 0.1912294179201126
Epoch: 193 Loss: 0.19080278277397156
Epoch: 194 Loss: 0.19037967920303345
Epoch: 195 Loss: 0.18996010720729828
Epoch: 196 Loss: 0.18954390287399292
Epoch: 197 Loss: 0.18913114070892334
Epoch: 198 Loss: 0.1887216866016388
Epoch: 199 Loss: 0.18831555545330048
Epoch: 200 Loss: 0.1879126876592636
Epoch: 201 Loss: 0.18751300871372223
Epoch: 202 Loss: 0.18711651861667633
Epoch: 203 Loss: 0.18672315776348114
Epoch: 204 Loss: 0.18633288145065308
Epoch: 205 Loss: 0.18594568967819214
Epoch: 206 Loss: 0.18556147813796997
Epoch: 207 Loss: 0.18518026173114777
Epoch: 208 Loss: 0.18480198085308075
Epoch: 209 Loss: 0.18442660570144653
Epoch: 210 Loss: 0.18405407667160034
Epoch: 211 Loss: 0.18368437886238098
Epoch: 212 Loss: 0.18331748247146606
Epoch: 213 Loss: 0.1829533576965332
Epoch: 214 Loss: 0.1825919896364212
Epoch: 215 Loss: 0.1822332739830017
Epoch: 216 Loss: 0.1818772405385971
Epoch: 217 Loss: 0.18152381479740143
Epoch: 218 Loss: 0.18117299675941467
Epoch: 219 Loss: 0.18082477152347565
Epoch: 220 Loss: 0.18047906458377838
Epoch: 221 Loss: 0.18013589084148407
Epoch: 222 Loss: 0.17979513108730316
Epoch: 223 Loss: 0.17945687472820282
Epoch: 224 Loss: 0.17912103235721588
Epoch: 225 Loss: 0.17878757417201996
Epoch: 226 Loss: 0.17845647037029266
Epoch: 227 Loss: 0.1781277358531952
Epoch: 228 Loss: 0.17780129611492157
Epoch: 229 Loss: 0.1774771362543106
Epoch: 230 Loss: 0.1771552413702011
Epoch: 231 Loss: 0.1768355816602707
Epoch: 232 Loss: 0.17651814222335815
Epoch: 233 Loss: 0.17620286345481873
Epoch: 234 Loss: 0.1758897602558136
Epoch: 235 Loss: 0.1755787879228592
Epoch: 236 Loss: 0.1752699464559555
Epoch: 237 Loss: 0.17496317625045776
Epoch: 238 Loss: 0.17465843260288239
Epoch: 239 Loss: 0.17435579001903534
Epoch: 240 Loss: 0.17405515909194946
Epoch: 241 Loss: 0.17375652492046356
Epoch: 242 Loss: 0.17345987260341644
Epoch: 243 Loss: 0.17316517233848572
Epoch: 244 Loss: 0.1728724092245102
Epoch: 245 Loss: 0.17258156836032867
Epoch: 246 Loss: 0.17229260504245758
Epoch: 247 Loss: 0.1720055341720581
Epoch: 248 Loss: 0.17172031104564667
Epoch: 249 Loss: 0.17143693566322327
Epoch: 250 Loss: 0.17115534842014313

In [292]:
model.linear.weight, model.linear.bias

(Parameter containing:
 tensor([[ 0.2866,  0.0893,  0.3605,  0.2850,  0.2388,  0.2911,  0.1357,  0.1525,
          -0.0226, -0.0808,  0.1767,  0.0290,  0.1002,  0.1332,  0.1054, -0.0972,
           0.0509,  0.0069, -0.0870, -0.0530,  0.2528,  0.1460,  0.3322,  0.1531,
           0.0485,  0.3162,  0.0988,  0.3483,  0.2413, -0.0244]],
        requires_grad=True),
 Parameter containing:
 tensor([-0.0237], requires_grad=True))

In [293]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy}')

Accuracy: 0.6218836307525635

In [294]:
class MultiLayerNN(nn.Module):
  def __init__(self, num_features):
    super().__init__()

    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, num_features):
    out = self.network(num_features)
    return out

In [295]:
learning_rate = 0.1
epochs = 25

In [296]:
loss_function = nn.BCELoss()

In [297]:
# model creation

model = MultiLayerNN(num_features=X_train_tensor.shape[1])
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

for epoch in range(epochs):
  y_pred = model(X_train_tensor)

  # calculate loss
  loss = loss_function(y_pred, y_train_tensor.view(-1, 1))

  # clear gradients

  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # optimizer

  optimizer.step()

  print(f'Epoch: {epoch +  1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.7127346992492676
Epoch: 2, Loss: 0.7041569352149963
Epoch: 3, Loss: 0.6970515847206116
Epoch: 4, Loss: 0.691001832485199
Epoch: 5, Loss: 0.685539186000824
Epoch: 6, Loss: 0.680823028087616
Epoch: 7, Loss: 0.6768814921379089
Epoch: 8, Loss: 0.6734201908111572
Epoch: 9, Loss: 0.6703484654426575
Epoch: 10, Loss: 0.6674447655677795
Epoch: 11, Loss: 0.6646389365196228
Epoch: 12, Loss: 0.6618627905845642
Epoch: 13, Loss: 0.6589930057525635
Epoch: 14, Loss: 0.6560086607933044
Epoch: 15, Loss: 0.6525481343269348
Epoch: 16, Loss: 0.6485280394554138
Epoch: 17, Loss: 0.6438613533973694
Epoch: 18, Loss: 0.6379188895225525
Epoch: 19, Loss: 0.630275309085846
Epoch: 20, Loss: 0.6222107410430908
Epoch: 21, Loss: 0.6132511496543884
Epoch: 22, Loss: 0.6030568480491638
Epoch: 23, Loss: 0.5919068455696106
Epoch: 24, Loss: 0.5799190998077393
Epoch: 25, Loss: 0.5671172142028809

In [298]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(accuracy)

tensor(0.7105)